"""empty message

Revision ID: 4abb2fa1dcd5
Revises: 7b65a814d700
Create Date: 2018-04-09 15:06:29.445366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4abb2fa1dcd5'
down_revision = '7b65a814d700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('end', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('start', sa.DateTime(), nullable=True))
    op.drop_column('task', 'starttime')
    op.drop_column('task', 'endtime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('endtime', mysql.DATETIME(), nullable=True))
    op.add_column('task', sa.Column('starttime', mysql.DATETIME(), nullable=True))
    op.drop_column('task', 'start')
    op.drop_column('task', 'end')
    # ### end Alembic commands ###
